# Generated by Django 6.0.1 on 2026-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('paginas', models.IntegerField()),
                ('editorial', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes-libros/')),
            ],
        ),
    ]
